/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "%s of %s": {                                    "en": "%s of %s",                                        "de": "%s von %s",                                       "ru": "%s из %s",                                        "pt": "%s de %s",                                        "nl": "%s van %s",                                       "fr": "%s de %s",                                        "it": "%s di %s",                                        "es": "%s de %s",                                        "pl": "%s z %s",                                         "zh-cn": "%s %s"},
    "Advanced settings": {                           "en": "Advanced settings",                               "de": "Erweiterte Einstellungen",                        "ru": "Расширенные настройки",                           "pt": "Configurações avançadas",                         "nl": "Geavanceerde instellingen",                       "fr": "Réglages avancés",                                "it": "Impostazioni avanzate",                           "es": "Ajustes avanzados",                               "pl": "Zaawansowane ustawienia",                         "zh-cn": "高级设置"},
    "Analog mode": {                                 "en": "Analog mode",                                     "de": "Analogmodus",                                     "ru": "Аналоговый режим",                                "pt": "Modo analógico",                                  "nl": "Analoge modus",                                   "fr": "Mode analogique",                                 "it": "Modalità analogica",                              "es": "Modo analógico",                                  "pl": "Tryb analogowy",                                  "zh-cn": "模拟模式"},
    "Check license": {                               "en": "Check license",                                   "de": "Lizenz prüfen",                                   "ru": "Проверить лицензию",                              "pt": "Verifique a licença",                             "nl": "Controleer licentie",                             "fr": "Vérifier la licence",                             "it": "Controlla la licenza",                            "es": "Verificar licencia",                              "pl": "Sprawdź licencję",                                "zh-cn": "检查许可证"},
    "Debug": {                                       "en": "Debug",                                           "de": "Debuggen",                                        "ru": "Отладка",                                         "pt": "Depurar",                                         "nl": "debug",                                           "fr": "Déboguer",                                        "it": "mettere a punto",                                 "es": "Depurar",                                         "pl": "Odpluskwić",                                      "zh-cn": "除错"},
    "Detecting...": {                                "en": "Detecting...",                                    "de": "Erkennen ...",                                    "ru": "Детектирование ...",                              "pt": "Detecção...",                                     "nl": "Het ontdekken van ...",                           "fr": "Détecter ...",                                    "it": "Rilevamento ...",                                 "es": "Detector...",                                     "pl": "Wykrywanie ...",                                  "zh-cn": "正在检测..."},
    "Done.": {                                       "en": "Done.",                                           "de": "Erledigt.",                                       "ru": "Готово.",                                         "pt": "Feito.",                                          "nl": "Gedaan.",                                         "fr": "Terminé.",                                        "it": "Fatto.",                                          "es": "Hecho.",                                          "pl": "Gotowe.",                                         "zh-cn": "做完了"},
    "Found": {                                       "en": "Found",                                           "de": "Gefunden",                                        "ru": "Найденный",                                       "pt": "Encontrado",                                      "nl": "gevonden",                                        "fr": "A trouvé",                                        "it": "Trovato",                                         "es": "Encontró",                                        "pl": "Uznany",                                          "zh-cn": "找到了"},
    "Found %s devices, new of them %s devices.": {   "en": "Found %s device(s), new of them: %s device(s).",  "de": "%s Gerät(e) gefunden, neue davon: %s Gerät(e).",  "ru": "Найдено %s устройств(о), новые из них: %s устройств(о).", "pt": "Encontrado %s dispositivos, novos deles: %s dispositivos.", "nl": "%s apparaten gevonden, nieuwe daarvan: %s apparaten.", "fr": "%s périphériques trouvés, nouveaux d'entre eux %s périphériques.", "it": "Trovato dispositivi di %s, nuovi di loro %s dispositivi.", "es": "Encontré %s dispositivos, nuevos de ellos %s dispositivos.", "pl": "Znaleziono urządzenia %s, nowe z nich %s urządzeń.", "zh-cn": "找到%s台设备，其中的新设备：%s台设备。"},
    "LCN IP": {                                      "en": "LCN IP",                                          "de": "LCN IP",                                          "ru": "LCN IP",                                          "pt": "IP LCN",                                          "nl": "LCN IP",                                          "fr": "LCN IP",                                          "it": "LCN IP",                                          "es": "LCN IP",                                          "pl": "LCN IP",                                          "zh-cn": "LCN IP"},
    "LCN Port": {                                    "en": "LCN Port",                                        "de": "LCN-Port",                                        "ru": "Порт LCN",                                        "pt": "Porta LCN",                                       "nl": "LCN-poort",                                       "fr": "Port LCN",                                        "it": "LCN Port",                                        "es": "Puerto LCN",                                      "pl": "Port LCN",                                        "zh-cn": "LCN端口"},
    "License %s with %s modules": {                  "en": "License %s with %s modules",                      "de": "Lizenz %s mit %s Modulen",                        "ru": "Лицензия %s с %s модулями",                       "pt": "Licença %s com %s modules",                       "nl": "Licentie %s met %s modules",                      "fr": "Licence %s avec les modules %s",                  "it": "Licenza %s con moduli %s",                        "es": "Licencia %s con %s modulos",                      "pl": "Licencja %s z modułami %s",                       "zh-cn": "使用%s模块许可%s"},
    "License:": {                                    "en": "License key",                                     "de": "License Key",                                     "ru": "Лицензионный ключ",                               "pt": "Chave de licença",                                "nl": "Licentiesleutel",                                 "fr": "Clé de licence",                                  "it": "Chiave di licenza",                               "es": "Clave de licencia",                               "pl": "Klucz licencyjny",                                "zh-cn": "注册码"},
    "Max module for scan": {                         "en": "Max module for scan",                             "de": "Max-Modul zum Scannen",                           "ru": "Максимальный модуль для сканирования",            "pt": "Módulo máximo para digitalização",                "nl": "Max module voor scannen",                         "fr": "Max module pour scan",                            "it": "Modulo max per scansione",                        "es": "Max módulo para escanear",                        "pl": "Max moduł do skanowania",                         "zh-cn": "最大扫描模块"},
    "Modules": {                                     "en": "Modules",                                         "de": "Module",                                          "ru": "Модули",                                          "pt": "Módulos",                                         "nl": "modules",                                         "fr": "Modules",                                         "it": "moduli",                                          "es": "Módulos",                                         "pl": "Moduły",                                          "zh-cn": "模组"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Password repeat": {                             "en": "Password repeat",                                 "de": "Passwort wiederholen",                            "ru": "Повтор пароля",                                   "pt": "Repetição de senha",                              "nl": "Wachtwoord herhalen",                             "fr": "Répéter le mot de passe",                         "it": "Ripetizione della password",                      "es": "Repite la contraseña",                            "pl": "Powtórz hasło",                                   "zh-cn": "密码重复"},
    "Ping Interval(sec)": {                          "en": "Ping Interval(sec)",                              "de": "Ping-Intervall (Sek)",                            "ru": "Интервал Ping (сек)",                             "pt": "Intervalo de Ping (s)",                           "nl": "Ping-interval (sec)",                             "fr": "Intervalle de Ping (sec)",                        "it": "Intervallo di ping (sec)",                        "es": "Intervalo de ping (seg)",                         "pl": "Ping Interval (s)",                               "zh-cn": "ping间隔（秒）"},
    "Ping response timeout(ms)": {                   "en": "Ping response timeout(ms)",                       "de": "Ping-Antwortzeitüberschreitung (ms)",             "ru": "Тайм-аут ответа пинга (мс)",                      "pt": "Tempo limite de resposta de ping (ms)",           "nl": "Ping-responstijd (ms)",                           "fr": "Délai de réponse Ping (ms)",                      "it": "Timeout risposta ping (ms)",                      "es": "Tiempo de espera de respuesta de ping (ms)",      "pl": "Limit czasu odpowiedzi Ping (ms)",                "zh-cn": "Ping响应超时（毫秒）"},
    "Read all states at start": {                    "en": "Read all states at start",                        "de": "Alle Status beim Start lesen",                    "ru": "Читать все состояния при старте",                   "pt": "Leia todos os estados no início",                 "nl": "Lees alle staten bij het begin",                  "fr": "Lire tous les états au début",                    "it": "Leggi tutti gli stati all'inizio",                "es": "Lea todos los estados al inicio",                 "pl": "Przeczytaj wszystkie stany na początku",          "zh-cn": "开始阅读所有状态"},
    "Read config": {                                 "en": "Read config",                                     "de": "Konfiguration lesen",                             "ru": "Читать конфиг",                                   "pt": "Read config",                                     "nl": "Configuratie lezen",                              "fr": "Lire config",                                     "it": "Leggi config",                                    "es": "Leer config",                                     "pl": "Przeczytaj konfigurację",                         "zh-cn": "读取配置"},
    "Reading info...": {                             "en": "Reading info...",                                 "de": "Info lesen ...",                                  "ru": "Информация для чтения ...",                       "pt": "Lendo informações ...",                           "nl": "Informatie lezen ...",                            "fr": "Lire des infos ...",                              "it": "Informazioni sulla lettura ...",                  "es": "Leer información ...",                            "pl": "Czytanie informacji ...",                         "zh-cn": "正在阅读信息..."},
    "Reconnect interval(sec)": {                     "en": "Reconnect interval(sec)",                         "de": "Wiederherstellungsintervall (Sek)",               "ru": "Интервал повторного подключения (сек)",           "pt": "Reconnect interval (sec)",                        "nl": "Verbindingsinterval opnieuw verbinden (sec)",     "fr": "Intervalle de reconnexion (sec)",                 "it": "Intervallo di riconnessione (sec)",               "es": "Intervalo de reconexión (seg)",                   "pl": "Interwał ponownego połączenia (s)",               "zh-cn": "重新连接间隔（秒）"},
    "Relays": {                                      "en": "Relays",                                          "de": "Relais",                                          "ru": "Реле",                                            "pt": "Relés",                                           "nl": "relays",                                          "fr": "Des relais",                                      "it": "Relè",                                            "es": "Relés",                                           "pl": "Przekaźniki",                                     "zh-cn": "继电器"},
    "Response timeout(ms)": {                        "en": "Response timeout(ms)",                            "de": "Reaktionszeit (ms)",                              "ru": "Тайм-аут ответа (мс)",                            "pt": "Tempo limite de resposta (ms)",                   "nl": "Response timeout (ms)",                           "fr": "Délai de réponse (ms)",                           "it": "Timeout di risposta (ms)",                        "es": "Tiempo de espera de respuesta (ms)",              "pl": "Czas reakcji (ms)",                               "zh-cn": "响应超时（毫秒）"},
    "Scan": {                                        "en": "Scan",                                            "de": "Scan",                                            "ru": "Сканирование",                                    "pt": "Scan",                                            "nl": "Scannen",                                         "fr": "Balayage",                                        "it": "Scansione",                                       "es": "Escanear",                                        "pl": "Skandować",                                       "zh-cn": "扫瞄"},
    "Scan finished": {                               "en": "Scan finished",                                   "de": "Scan abgeschlossen",                              "ru": "Сканирование завершено",                          "pt": "Scan terminado",                                  "nl": "Scannen voltooid",                                "fr": "Scan terminé",                                    "it": "Scansione finita",                                "es": "Escaneo terminado",                               "pl": "Skanowanie zakończone",                           "zh-cn": "扫描完成"},
    "Scan progress": {                               "en": "Scan progress",                                   "de": "Fortschritt",                                     "ru": "Прогресс сканирования",                           "pt": "Progresso de digitalização",                      "nl": "Scan voortgang",                                  "fr": "Progression de l'analyse",                        "it": "Scansione dei progressi",                         "es": "Progreso del análisis",                           "pl": "Postęp skanowania",                               "zh-cn": "扫描进度"},
    "Scan step": {                                   "en": "Scan step",                                       "de": "Schritt",                                         "ru": "Шаг сканирования",                                "pt": "Etapa de digitalização",                          "nl": "Scanstap",                                        "fr": "Étape de l'analyse",                              "it": "Passo di scansione",                              "es": "Paso de escaneo",                                 "pl": "Krok skanowania",                                 "zh-cn": "扫描步骤"},
    "Service is offline. Please try later.": {       "en": "Service is offline or no internet available. Please try later or check the internet connection.", "de": "Service ist momentan nicht erreichbar oder keine Internetverbindung vorhanden. Bitte fersuchen Sie später noch ein mal oder prüfen Sie die Internetverbindung.", "ru": "Сервис сейчас недоступен или нет интернет соединения. Попробуйте попозже или проверте интеренет соединение.", "pt": "O serviço está offline ou não há internet disponível. Por favor tente mais tarde ou confira a conexão com a internet.", "nl": "Service is offline of geen internet beschikbaar. Probeer het later opnieuw of controleer de internetverbinding.", "fr": "Le service est hors ligne ou pas disponible sur Internet. Veuillez réessayer plus tard ou vérifier la connexion Internet.", "it": "Il servizio è offline o non disponibile su Internet. Si prega di provare più tardi o controllare la connessione internet.", "es": "El servicio está fuera de línea o no hay internet disponible. Por favor intente más tarde o verifique la conexión a internet.", "pl": "Usługa jest niedostępna lub nie ma dostępu do Internetu. Spróbuj później lub sprawdź połączenie internetowe.", "zh-cn": "服务处于离线状态或没有可用的互联网。 请稍后再试或检查互联网连接。"},
    "User": {                                        "en": "User",                                            "de": "Benutzer",                                        "ru": "Пользователь",                                    "pt": "Do utilizador",                                   "nl": "Gebruiker",                                       "fr": "Utilisateur",                                     "it": "Utente",                                          "es": "Usuario",                                         "pl": "Użytkownik",                                      "zh-cn": "用户"},
    "instruction": {
        "en": "You can use only 10 modules for free. To enable more modules, you must buy the license for LCN.<br>You can get the license on <a href='https://iobroker.net/accountLicenses' target='_blank'>iobroker.net</a> after short registration.",
        "de": "Sie können nur 10 Module kostenlos verwenden. Um weitere Module zu aktivieren, müssen Sie die Lizenz für LCN erwerben. <br> Sie können die Lizenz unter <a href='https://iobroker.net/accountLicenses' target='_blank'> iobroker.net </a> nach kurzer Anmeldung erwerben.",
        "ru": "Вы можете использовать только 10 модулей бесплатно. Чтобы включить больше модулей, вы должны купить лицензию на LCN. <br> Вы можете получить лицензию на <a href='https://iobroker.net/accountLicenses' target='_blank'> iobroker.net </a> после короткой регистрации.",
        "pt": "Você pode usar apenas 10 módulos gratuitamente. Para ativar mais módulos, você deve comprar a licença para LCN. <br> Você pode obter a licença em <a href='https://iobroker.net/accountLicenses' target='_blank'> iobroker.net </a> após registro curto.",
        "nl": "U kunt slechts 10 modules gratis gebruiken. Als u meer modules wilt inschakelen, moet u de licentie voor LCN kopen. <br> U kunt de licentie verkrijgen op <a href='https://iobroker.net/accountLicenses' target='_blank'> iobroker.net </a> na korte registratie.",
        "fr": "Vous ne pouvez utiliser que 10 modules gratuitement. Pour activer davantage de modules, vous devez acheter la licence pour LCN. <br> Vous pouvez obtenir cette licence sur <a href='https://iobroker.net/accountLicenses' target='_blank'> iobroker.net </a>. après une courte inscription.",
        "it": "Puoi utilizzare solo 10 moduli gratuitamente. Per abilitare più moduli, è necessario acquistare la licenza per LCN. <br> È possibile ottenere la licenza su <a href='https://iobroker.net/accountLicenses' target='_blank'> iobroker.net </a> dopo una breve registrazione.",
        "es": "Puedes usar solo 10 módulos gratis. Para habilitar más módulos, debe comprar la licencia para LCN. <br> Puede obtener la licencia en <a href='https://iobroker.net/accountLicenses' target='_blank'> iobroker.net </a> Después de un breve registro.",
        "pl": "Możesz użyć tylko 10 modułów za darmo. Aby włączyć więcej modułów, musisz kupić licencję na LCN. <br> Możesz uzyskać licencję na <a href='https://iobroker.net/accountLicenses' target='_blank'> iobroker.net </a> po krótkiej rejestracji.",
        "zh-cn": "您只能免费使用10个模块。 要启用更多模块，必须购买LCN的许可证。<br>您可以在<a href='https://iobroker.net/accountLicenses' target='_blank'>iobroker.net</a>上获得许可证。 短暂注册后。"},
    "Rescan": {
        "en": "Re-scan",
        "de": "Erneut scannen",
        "ru": "Повторное сканирование",
        "pt": "Verificar novamente",
        "nl": "Herscannen",
        "fr": "Re-scan",
        "it": "Re-scan",
        "es": "Vuelva a escanear",
        "pl": "Ponownie skanuj",
        "zh-cn": "重新扫描"
    },
    "Connect timeout(ms)": {
        "en": "Connect timeout(ms)",
        "de": "Verbindungs-Timeout (ms)",
        "ru": "Тайм-аут соединения (мс)",
        "pt": "Tempo limite de conexão (ms)",
        "nl": "Time-out verbinden (ms)",
        "fr": "Délai de connexion (ms)",
        "it": "Connetti timeout (ms)",
        "es": "Tiempo de espera de conexión (ms)",
        "pl": "Limit czasu połączenia (ms)",
        "zh-cn": "连接超时（毫秒）"
    },
    "Scan response timeout(ms)": {
        "en": "Scan response timeout(ms)",
        "de": "Scan-Antwortzeitlimit (ms)",
        "ru": "Время ожидания ответа сканирования (мс)",
        "pt": "Tempo limite de resposta da verificação (ms)",
        "nl": "Time-out scanrespons (ms)",
        "fr": "Délai de réponse de l'analyse (ms)",
        "it": "Timeout risposta scansione (ms)",
        "es": "Tiempo de espera de respuesta de escaneo (ms)",
        "pl": "Limit czasu odpowiedzi skanowania (ms)",
        "zh-cn": "扫描响应超时（毫秒）"
    },
    "IN/OUT Relays are the same": {
        "en": "IN/OUT Relays are the same",
        "de": "IN/OUT-Relais sind gleich",
        "ru": "Реле IN/OUT одни и те же",
        "pt": "Os relés IN/OUT são os mesmos",
        "nl": "IN / UIT Relais zijn hetzelfde",
        "fr": "Les relais IN/OUT sont les mêmes",
        "it": "I relè IN/OUT sono uguali",
        "es": "Los relés IN/OUT son iguales",
        "pl": "Przekaźniki WE/WY są takie same",
        "zh-cn": "输入/输出继电器相同"
    },
    "Use license manager": {
        "en": "Use license manager",
        "de": "Lizenzmanager verwenden",
        "ru": "Использовать менеджер лицензий",
        "pt": "Use o gerenciador de licenças",
        "nl": "Licentiebeheer gebruiken",
        "fr": "Utiliser le gestionnaire de licences",
        "it": "Usa il gestore delle licenze",
        "es": "Usar administrador de licencias",
        "pl": "Użyj menedżera licencji",
        "zh-cn": "使用许可证管理器"
    },
    "Serial number": {
        "en": "Serial number",
        "de": "Seriennummer",
        "ru": "Серийный номер",
        "pt": "Número de série",
        "nl": "Serienummer",
        "fr": "Numéro de série",
        "it": "Numero di serie",
        "es": "Número de serie",
        "pl": "Numer seryjny",
        "zh-cn": "序列号"
    },
    "Suitable license found": {
        "en": "Suitable license found",
        "de": "Passende Lizenz gefunden",
        "ru": "Найдена подходящая лицензия",
        "pt": "Licença adequada encontrada",
        "nl": "Geschikte licentie gevonden",
        "fr": "Licence appropriée trouvée",
        "it": "Trovata licenza adatta",
        "es": "Licencia adecuada encontrada",
        "pl": "Znaleziono odpowiednią licencję",
        "zh-cn": "找到合适的许可证"
    },
    "Suitable license not found": {
        "en": "Suitable license not found",
        "de": "Passende Lizenz nicht gefunden",
        "ru": "Подходящая лицензия не найдена",
        "pt": "Licença adequada não encontrada",
        "nl": "Geschikte licentie niet gevonden",
        "fr": "Licence appropriée introuvable",
        "it": "Licenza adatta non trovata",
        "es": "Licencia adecuada no encontrada",
        "pl": "Nie znaleziono odpowiedniej licencji",
        "zh-cn": "未找到合适的许可证"
    }
};
